import sys
import subprocess
import os
import random
import time
import playsound as sound
from decouple import config
from gtts import gTTS


while True:
    IP_NETWORK = config("IP_NETWORK")
    IP_DEVICES = config("IP_DEVICES")

    proc = subprocess.Popen(["ping", IP_NETWORK], stdout=subprocess.PIPE)

    while True:
        line = proc.stdout.readline()
        if not line:
            break
        connected_ip = line.decode("utf-8").split()

        if len(connected_ip) > 2:
            connected_ip = connected_ip[2]

            if connected_ip == IP_DEVICES:
                audio_string = "IPhone XI is Online..."
                # init google's text-to-speech module
                tts = gTTS(text=audio_string, lang="en-us", slow=False)
                # generate a filename for the audio file generated by google
                audio_file = f"./text-to-speech-audio/ping-audio-{str(random.randint(1, 1000))}.mp3"
                # announce/play the generated audio
                sound.playsound(audio_file)
        time.sleep(1)
    time.sleep(1)
