import speech_recognition as sr
import os
import random
import playsound
import colorama
from gtts import gTTS
from gtts.tts import gTTSError


class SpeechAssistant:
    def __init__(self, masters_name, assistants_name):
        self.master_name = masters_name
        self.assistant_name = assistants_name

    def listen_to_audio(self, ask=None):
        with sr.Microphone() as source:
            voice_text = ""
            try:
                r = sr.Recognizer()
                # calibrate (source) microphone
                r.adjust_for_ambient_noise(source)

                if ask:
                    # announce/play something before listening to user
                    self.speak(ask)

                # listening
                audio = r.listen(source)
                # convert to text/string data
                voice_text = r.recognize_google(audio)

            except sr.UnknownValueError:
                return voice_text
            except sr.RequestError:
                self.speak(
                    "Sorry! My speech service is not available at the moment.")
            except gTTSError as gts_err:
                print(gts_err.infer_msg())
            except Exception as ex:
                print(ex.__cause__)

            print(f"\033[1;40;42m{self.master_name}: {voice_text}")
            return voice_text

    def speak(self, audio_string):
        if audio_string.strip():
            # init google's text-to-speech module
            tts = gTTS(text=audio_string, lang="en", slow=False)

            # generate a filename for the audio file generated by google
            audio_file = f"assistants-audio-{str(random.randint(1, 1000))}.mp3"
            tts.save(audio_file)

            # announce/play the generated audio
            print(f"\033[1;40;46m{self.assistant_name}: {audio_string}")
            playsound.playsound(audio_file)

            # delete the audio file after announcing to save mem space
            os.remove(audio_file)
